
import type { User, Job, Bid, Comment } from './types';

// Updated to use centralized placeholder images for anonymity
const userAvatars: Record<string, string> = {
  'user-1': 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwZXJzb24lMjBmYWNlfGVufDB8fHx8MTc1ODY5NTM3OHww&ixlib=rb-4.1.0&q=80&w=1080',
  'user-2': 'https://images.unsplash.com/photo-1725028748781-7adb1df9a943?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxwZXJzb24lMjBmYWNlfGVufDB8fHx8MTc1ODY5NTM3OHww&ixlib=rb-4.1.0&q=80&w=1080',
  'user-3': 'https://images.unsplash.com/photo-1710974481447-fb001ad9ad5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxwZXJzb24lMjBmYWNlfGVufDB8fHx8MTc1ODY5NTM3OHww&ixlib=rb-4.1.0&q=80&w=1080',
  'user-4': 'https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxwZXJzb24lMjBmYWNlfGVufDB8fHx8MTc1ODY5NTM3OHww&ixlib=rb-4.1.0&q=80&w=1080',
  'user-5': 'https://images.unsplash.com/photo-1521146764736-56c929d59c83?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxwZXJzb24lMjBmYWNlfGVufDB8fHx8MTc1ODY5NTM3OHww&ixlib=rb-4.1.0&q=80&w=1080',
  'user-6': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8cGVyc29uJTIwZmFjZXxlbnwwfHx8fDE3NTg2OTUzNzh8MA&ixlib=rb-4.1.0&q=80&w=1080',
  'user-7': 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMXx8cGVyc29uJTIwZmFjZXxlbnwwfHx8fDE3NTg2OTUzNzh8MA&ixlib=rb-4.1.0&q=80&w=1080',
  'user-8': 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMnx8cGVyc29uJTIwZmFjZXxlbnwwfHx8fDE3NTg2OTUzNzh8MA&ixlib=rb-4.1.0&q=80&w=1080',
};


export const users: User[] = [
  {
    id: 'user-1',
    name: 'Alex Johnson',
    anonymousId: 'Installer #A1B2',
    email: 'alex.j@example.com',
    avatarUrl: userAvatars['user-1'],
    pincode: '110001',
    roles: ['Job Giver', 'Installer'],
    installerProfile: {
      tier: 'Gold',
      points: 1250,
      skills: ['IP Cameras', 'NVR Setup', 'Remote Viewing', 'Access Control', 'Structured Cabling'],
      jobsCompleted: 35,
      rating: 4.9,
      reviews: 28,
      verified: true,
      reputationHistory: [
        { month: 'Apr', points: 200 },
        { month: 'May', points: 150 },
        { month: 'Jun', points: 300 },
        { month: 'Jul', points: 250 },
        { month: 'Aug', points: 150 },
        { month: 'Sep', points: 200 },
      ]
    },
  },
  {
    id: 'user-2',
    name: 'Brenda Smith',
    anonymousId: 'Job Giver #C3D4',
    email: 'brenda.s@example.com',
    avatarUrl: userAvatars['user-2'],
    pincode: '400001',
    roles: ['Job Giver'],
  },
  {
    id: 'user-3',
    name: 'Carlos Diaz',
    anonymousId: 'Installer #E5F6',
    email: 'carlos.d@example.com',
    avatarUrl: userAvatars['user-3'],
    pincode: '500001',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Silver',
      points: 600,
      skills: ['Analog Cameras', 'DVR Configuration', 'Cabling', 'Troubleshooting'],
      jobsCompleted: 15,
      rating: 4.7,
      reviews: 12,
      verified: true,
      reputationHistory: [
        { month: 'Apr', points: 100 },
        { month: 'May', points: 50 },
        { month: 'Jun', points: 150 },
        { month: 'Jul', points: 100 },
        { month: 'Aug', points: 100 },
        { month: 'Sep', points: 100 },
      ]
    },
  },
  {
    id: 'user-4',
    name: 'Diana Prince',
    anonymousId: 'Installer #G7H8',
    email: 'diana.p@example.com',
    avatarUrl: userAvatars['user-4'],
    pincode: '600001',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Bronze',
      points: 250,
      skills: ['IP Cameras', 'Basic Setup', 'Wireless Cameras'],
      jobsCompleted: 5,
      rating: 4.5,
      reviews: 4,
      verified: false,
      reputationHistory: [
        { month: 'Apr', points: 0 },
        { month: 'May', points: 50 },
        { month: 'Jun', points: 50 },
        { month: 'Jul', points: 75 },
        { month: 'Aug', points: 25 },
        { month: 'Sep', points: 50 },
      ]
    },
  },
  {
    id: 'user-5',
    name: 'Ethan Hunt',
    anonymousId: 'Installer #I9J0',
    email: 'ethan.h@example.com',
    avatarUrl: userAvatars['user-5'],
    pincode: '110031',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Platinum',
      points: 2500,
      skills: ['Advanced IP Systems', 'VMS', 'Analytics', 'Access Control', 'Fiber Optics'],
      jobsCompleted: 75,
      rating: 5.0,
      reviews: 68,
      verified: true,
      reputationHistory: [
        { month: 'Apr', points: 400 },
        { month: 'May', points: 500 },
        { month: 'Jun', points: 450 },
        { month: 'Jul', points: 350 },
        { month: 'Aug', points: 400 },
        { month: 'Sep', points: 400 },
      ]
    },
  },
  {
    id: 'user-6',
    name: 'Fiona Glenanne',
    anonymousId: 'Job Giver #K1L2',
    email: 'fiona.g@example.com',
    avatarUrl: userAvatars['user-6'],
    pincode: '400050',
    roles: ['Job Giver'],
  },
  {
    id: 'user-7',
    name: 'George Mason',
    anonymousId: 'Installer #M3N4',
    email: 'george.m@example.com',
    avatarUrl: userAvatars['user-7'],
    pincode: '800001',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Gold',
      points: 1100,
      skills: ['Thermal Cameras', 'NVR Setup', 'PTZ Cameras', 'Wireless Bridge'],
      jobsCompleted: 28,
      rating: 4.8,
      reviews: 25,
      verified: true,
      reputationHistory: [
         { month: 'Apr', points: 150 },
        { month: 'May', points: 200 },
        { month: 'Jun', points: 250 },
        { month: 'Jul', points: 150 },
        { month: 'Aug', points: 150 },
        { month: 'Sep', points: 200 },
      ]
    },
  },
  {
    id: 'user-8',
    name: 'Hannah Simone',
    anonymousId: 'Job Giver #O5P6',
    email: 'hannah.s@example.com',
    avatarUrl: userAvatars['user-8'],
    pincode: '500032',
    roles: ['Job Giver', 'Installer'],
    installerProfile: {
      tier: 'Silver',
      points: 450,
      skills: ['IP Cameras', 'Home Automation', 'Basic Setup'],
      jobsCompleted: 10,
      rating: 4.6,
      reviews: 9,
      verified: false,
      reputationHistory: [
        { month: 'Apr', points: 50 },
        { month: 'May', points: 100 },
        { month: 'Jun', points: 100 },
        { month: 'Jul', points: 50 },
        { month: 'Aug', points: 100 },
        { month: 'Sep', points: 50 },
      ]
    },
  },
];

const comments: {[key: string]: Comment[]} = {
  'JOB-20240920-1A3B': [
    {
      id: 'comment-1-1',
      author: { id: 'user-3', name: 'Carlos Diaz', anonymousId: 'Installer #E5F6', avatarUrl: userAvatars['user-3'] },
      timestamp: new Date('2024-09-22T10:00:00Z'),
      content: "What brand of cameras are you planning to use? And is wiring already in place?",
    },
    {
      id: 'comment-1-2',
      author: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
      timestamp: new Date('2024-09-23T11:00:00Z'),
      content: "Hi Carlos, we're open to suggestions, but leaning towards Hikvision. No existing wiring, it needs to be run from scratch.",
    },
    {
      id: 'comment-1-3',
      author: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Installer #A1B2', avatarUrl: userAvatars['user-1'] },
      timestamp: new Date('2024-09-23T12:00:00Z'),
      content: "Is the building construction concrete or drywall? It will affect the cabling time.",
    },
     {
      id: 'comment-1-4',
      author: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
      timestamp: new Date('2024-09-23T13:00:00Z'),
      content: "It's a mix. Mostly drywall interiors with a concrete exterior.",
    }
  ],
  'JOB-20240924-4D5E': [
    {
      id: 'comment-5-1',
      author: { id: 'user-4', name: 'Diana Prince', anonymousId: 'Installer #G7H8', avatarUrl: userAvatars['user-4'] },
      timestamp: new Date('2024-09-23T14:00:00Z'),
      content: "Is this a single warehouse or multiple buildings?",
    },
     {
      id: 'comment-5-2',
      author: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
      timestamp: new Date('2024-09-24T09:00:00Z'),
      content: "It's a single large warehouse, approximately 50,000 sq ft.",
    }
  ],
};

const bids: {[key: string]: Bid[]} = {
  'JOB-20240920-1A3B': [
    {
      id: 'bid-1-1',
      installer: users[0],
      amount: 14000,
      timestamp: new Date('2024-09-21T18:00:00Z'),
      coverLetter: "With over 5 years of experience in IP camera systems and NVR setups, I can ensure a professional and clean installation. My bid includes all necessary cabling and configuration for remote viewing.",
    },
    {
      id: 'bid-1-2',
      installer: users[2],
      amount: 12500,
      timestamp: new Date('2024-09-22T09:00:00Z'),
      coverLetter: "I am confident I can complete this job to your satisfaction. I have experience with all major brands and can provide a cost-effective solution without compromising on quality.",
    },
    {
      id: 'bid-1-3',
      installer: users[4],
      amount: 18000,
      timestamp: new Date('2024-09-23T15:00:00Z'),
      coverLetter: "As a Platinum tier installer specializing in advanced systems, I can offer a premium installation with optimized camera placement and robust network configuration for flawless performance. My bid reflects a higher quality of service and components.",
    },
  ],
  'JOB-20240922-2B4C': [
     {
      id: 'bid-2-1',
      installer: users[3],
      amount: 9000,
      timestamp: new Date('2024-09-24T10:00:00Z'),
      coverLetter: "I can handle this upgrade efficiently. I'll ensure the new IP system is perfectly integrated.",
    },
  ],
  'JOB-20240915-3C5D': [
     {
      id: 'bid-3-1',
      installer: users[2],
      amount: 7500,
      timestamp: new Date('2024-09-14T10:00:00Z'),
      coverLetter: "I specialize in residential installations and can complete this quickly and cleanly. I guarantee a user-friendly setup for your mobile devices.",
    },
  ],
  'JOB-20240924-4D5E': [
     {
      id: 'bid-5-1',
      installer: users[4],
      amount: 48000,
      timestamp: new Date('2024-09-24T11:00:00Z'),
      coverLetter: "My team has extensive experience with large-scale warehouse projects. We use high-quality cabling and network gear to ensure reliable coverage across the entire area. We can also set up advanced analytics like line-crossing detection.",
    },
    {
      id: 'bid-5-2',
      installer: users[6],
      amount: 45000,
      timestamp: new Date('2024-09-24T12:00:00Z'),
      coverLetter: "I have installed systems in 5 warehouses in the last year. My bid is competitive and I can start next week.",
    },
  ],
  'JOB-20240917-5E6F': [
      {
      id: 'bid-6-1',
      installer: users[0],
      amount: 11000,
      timestamp: new Date('2024-09-22T14:00:00Z'),
      coverLetter: "I'm a Gold-tier installer with experience in retail environments. I can ensure minimal disruption to your business operations during the installation.",
    },
  ],
};


export const jobs: Job[] = [
  {
    id: 'JOB-20240920-1A3B',
    title: 'Install 8 IP Cameras for a 2-Story Office Building',
    description: "We are looking for a professional installer to set up a comprehensive surveillance system for our new office. The job involves installing 8 high-definition IP cameras covering both indoor and outdoor areas. The installer will also be responsible for setting up the Network Video Recorder (NVR), configuring motion detection, and enabling remote viewing access on mobile devices. All equipment will be provided, but the installer must supply their own tools and manage all cabling and mounting.",
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '400001, Mumbai',
    budget: { min: 10000, max: 20000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-09-30T23:59:59Z'),
    postedAt: new Date('2024-09-20T08:00:00Z'),
    bids: bids['JOB-20240920-1A3B'],
    comments: comments['JOB-20240920-1A3B'],
  },
  {
    id: 'JOB-20240922-2B4C',
    title: 'CCTV System Upgrade for a Retail Store',
    description: "Upgrading an existing 4-camera analog system to a modern 6-camera IP system. The job requires removing the old DVR and cameras, and installing new IP cameras with a new NVR. The installer should be able to advise on optimal camera placement for maximum coverage of the sales floor and entrance/exit points. Experience with POS integration is a plus.",
    jobGiver: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Job Giver #A1B2', avatarUrl: userAvatars['user-1'] },
    location: '110001, Delhi',
    budget: { min: 8000, max: 15000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-03T23:59:59Z'),
    postedAt: new Date('2024-09-22T09:00:00Z'),
    bids: bids['JOB-20240922-2B4C'],
    comments: [],
  },
  {
    id: 'JOB-20240915-3C5D',
    title: 'Residential 4-Camera Security Installation',
    description: "Seeking an installer for a standard 4-camera setup for a single-family home. Cameras to be placed at the front door, back door, driveway, and backyard. Simple setup with a DVR and mobile viewing required. Straightforward project for an experienced residential installer.",
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '600001, Chennai',
    budget: { min: 5000, max: 8000 },
    status: 'Awarded',
    awardedInstaller: 'user-3',
    deadline: new Date('2024-09-23T23:59:59Z'),
    postedAt: new Date('2024-09-15T11:00:00Z'),
    bids: bids['JOB-20240915-3C5D'],
    comments: [],
  },
  {
    id: 'JOB-20240825-4D6E',
    title: 'Maintenance and Check-up for existing system',
    description: "Need a technician to perform a full system check on our 16-camera setup. This includes cleaning lenses, checking all connections, ensuring the NVR is recording properly, and verifying that remote access is functional. The system is 2 years old.",
    jobGiver: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Job Giver #A1B2', avatarUrl: userAvatars['user-1'] },
    location: '500001, Hyderabad',
    budget: { min: 2000, max: 4000 },
    status: 'Completed',
    awardedInstaller: 'user-1',
    rating: 5,
    deadline: new Date('2024-08-26T23:59:59Z'),
    postedAt: new Date('2024-08-25T10:00:00Z'),
    bids: [],
    comments: [],
  },
  {
    id: 'JOB-20240924-4D5E',
    title: 'Install 32 PTZ Cameras in a Warehouse',
    description: 'We require a comprehensive surveillance solution for our new logistics warehouse. This involves installing 32 Pan-Tilt-Zoom (PTZ) cameras at strategic locations, setting up a centralized monitoring station with a Video Management System (VMS), and ensuring full wireless coverage across the facility. Only verified installers with experience in large-scale industrial projects should apply.',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '400050, Mumbai',
    budget: { min: 40000, max: 75000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-09T23:59:59Z'),
    postedAt: new Date('2024-09-24T14:00:00Z'),
    bids: bids['JOB-20240924-4D5E'],
    comments: comments['JOB-20240924-4D5E'],
  },
  {
    id: 'JOB-20240917-5E6F',
    title: 'Boutique Shop Camera Setup with Covert Cameras',
    description: 'Looking for a discreet security camera installation for a high-end boutique. The project requires 4-6 cameras, some of which must be covert or hidden. Aesthetics are very important. The system should be accessible remotely and have high-quality recording capabilities.',
    jobGiver: { id: 'user-8', name: 'Hannah Simone', anonymousId: 'Job Giver #O5P6', avatarUrl: userAvatars['user-8'] },
    location: '500032, Hyderabad',
    budget: { min: 9000, max: 18000 },
    status: 'Bidding Closed',
    deadline: new Date('2024-09-24T23:59:59Z'),
    postedAt: new Date('2024-09-17T16:00:00Z'),
    bids: bids['JOB-20240917-5E6F'],
    comments: [],
  },
  {
    id: 'JOB-20240922-6F7G',
    title: 'Solar-Powered Camera for Remote Farm',
    description: 'Need to install one or two solar-powered 4G cameras to monitor a remote agricultural property. The location has no power or Wi-Fi. The installer must provide a complete solution including the solar panel, battery, and 4G camera setup. ',
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '800001, Patna',
    budget: { min: 15000, max: 25000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-05T23:59:59Z'),
    postedAt: new Date('2024-09-22T13:00:00Z'),
    bids: [],
    comments: [],
  },
  {
    id: 'JOB-20240816-7G8H',
    title: 'Apartment Complex Access Control & CCTV',
    description: 'We are seeking bids for a full security overall for a 50-unit apartment building. This includes installing cameras in all common areas (lobbies, hallways, parking) and setting up an access control system for the main entrance. The job will be awarded to a company that can handle both aspects.',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '110001, Delhi',
    budget: { min: 80000, max: 150000 },
    status: 'In Progress',
    awardedInstaller: 'user-5',
    deadline: new Date('2024-09-10T23:59:59Z'),
    postedAt: new Date('2024-08-16T12:00:00Z'),
    bids: [],
    comments: [],
  },
];

    