import type { User, Job, Bid, Comment } from './types';
import { PlaceHolderImages } from './placeholder-images';

// Updated to use centralized placeholder images for anonymity
const userAvatars: Record<string, string> = {
  'user-1': PlaceHolderImages.find(p => p.id === 'avatar1')?.imageUrl || '',
  'user-2': PlaceHolderImages.find(p => p.id === 'avatar2')?.imageUrl || '',
  'user-3': PlaceHolderImages.find(p => p.id === 'avatar3')?.imageUrl || '',
  'user-4': PlaceHolderImages.find(p => p.id === 'avatar4')?.imageUrl || '',
  'user-5': PlaceHolderImages.find(p => p.id === 'avatar5')?.imageUrl || '',
  'user-6': PlaceHolderImages.find(p => p.id === 'avatar6')?.imageUrl || '',
  'user-7': PlaceHolderImages.find(p => p.id === 'avatar7')?.imageUrl || '',
  'user-8': PlaceHolderImages.find(p => p.id === 'avatar8')?.imageUrl || '',
};


export const users: User[] = [
  {
    id: 'user-1',
    name: 'Alex Johnson',
    anonymousId: 'Installer #A1B2',
    email: 'alex.j@example.com',
    avatarUrl: userAvatars['user-1'],
    pincode: '110001',
    roles: ['Job Giver', 'Installer'],
    installerProfile: {
      tier: 'Gold',
      points: 1250,
      skills: ['IP Cameras', 'NVR Setup', 'Remote Viewing', 'Access Control', 'Structured Cabling'],
      rating: 4.9,
      reviews: 28,
      verified: true,
      reputationHistory: [
        { month: 'Apr', points: 200 },
        { month: 'May', points: 150 },
        { month: 'Jun', points: 300 },
        { month: 'Jul', points: 250 },
        { month: 'Aug', points: 150 },
        { month: 'Sep', points: 200 },
      ]
    },
  },
  {
    id: 'user-2',
    name: 'Brenda Smith',
    anonymousId: 'Job Giver #C3D4',
    email: 'brenda.s@example.com',
    avatarUrl: userAvatars['user-2'],
    pincode: '400001',
    roles: ['Job Giver'],
  },
  {
    id: 'user-3',
    name: 'Carlos Diaz',
    anonymousId: 'Installer #E5F6',
    email: 'carlos.d@example.com',
    avatarUrl: userAvatars['user-3'],
    pincode: '500001',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Silver',
      points: 600,
      skills: ['Analog Cameras', 'DVR Configuration', 'Cabling', 'Troubleshooting'],
      rating: 4.7,
      reviews: 12,
      verified: true,
      reputationHistory: [
        { month: 'Apr', points: 100 },
        { month: 'May', points: 50 },
        { month: 'Jun', points: 150 },
        { month: 'Jul', points: 100 },
        { month: 'Aug', points: 100 },
        { month: 'Sep', points: 100 },
      ]
    },
  },
  {
    id: 'user-4',
    name: 'Diana Prince',
    anonymousId: 'Installer #G7H8',
    email: 'diana.p@example.com',
    avatarUrl: userAvatars['user-4'],
    pincode: '600001',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Bronze',
      points: 250,
      skills: ['IP Cameras', 'Basic Setup', 'Wireless Cameras'],
      rating: 4.5,
      reviews: 4,
      verified: false,
      reputationHistory: [
        { month: 'Apr', points: 0 },
        { month: 'May', points: 50 },
        { month: 'Jun', points: 50 },
        { month: 'Jul', points: 75 },
        { month: 'Aug', points: 25 },
        { month: 'Sep', points: 50 },
      ]
    },
  },
  {
    id: 'user-5',
    name: 'Ethan Hunt',
    anonymousId: 'Installer #I9J0',
    email: 'ethan.h@example.com',
    avatarUrl: userAvatars['user-5'],
    pincode: '110031',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Platinum',
      points: 2500,
      skills: ['Advanced IP Systems', 'VMS', 'Analytics', 'Access Control', 'Fiber Optics'],
      rating: 5.0,
      reviews: 68,
      verified: true,
      reputationHistory: [
        { month: 'Apr', points: 400 },
        { month: 'May', points: 500 },
        { month: 'Jun', points: 450 },
        { month: 'Jul', points: 350 },
        { month: 'Aug', points: 400 },
        { month: 'Sep', points: 400 },
      ]
    },
  },
  {
    id: 'user-6',
    name: 'Fiona Glenanne',
    anonymousId: 'Job Giver #K1L2',
    email: 'fiona.g@example.com',
    avatarUrl: userAvatars['user-6'],
    pincode: '400050',
    roles: ['Job Giver'],
  },
  {
    id: 'user-7',
    name: 'George Mason',
    anonymousId: 'Installer #M3N4',
    email: 'george.m@example.com',
    avatarUrl: userAvatars['user-7'],
    pincode: '800001',
    roles: ['Installer'],
    installerProfile: {
      tier: 'Gold',
      points: 1100,
      skills: ['Thermal Cameras', 'NVR Setup', 'PTZ Cameras', 'Wireless Bridge'],
      rating: 4.8,
      reviews: 25,
      verified: true,
      reputationHistory: [
         { month: 'Apr', points: 150 },
        { month: 'May', points: 200 },
        { month: 'Jun', points: 250 },
        { month: 'Jul', points: 150 },
        { month: 'Aug', points: 150 },
        { month: 'Sep', points: 200 },
      ]
    },
  },
  {
    id: 'user-8',
    name: 'Hannah Simone',
    anonymousId: 'Job Giver #O5P6',
    email: 'hannah.s@example.com',
    avatarUrl: userAvatars['user-8'],
    pincode: '500032',
    roles: ['Job Giver', 'Installer'],
    installerProfile: {
      tier: 'Silver',
      points: 450,
      skills: ['IP Cameras', 'Home Automation', 'Basic Setup'],
      rating: 4.6,
      reviews: 9,
      verified: false,
      reputationHistory: [
        { month: 'Apr', points: 50 },
        { month: 'May', points: 100 },
        { month: 'Jun', points: 100 },
        { month: 'Jul', points: 50 },
        { month: 'Aug', points: 100 },
        { month: 'Sep', points: 50 },
      ]
    },
  },
];

const comments: {[key: string]: Comment[]} = {
  'JOB-20240920-1A3B': [
    {
      id: 'comment-1-1',
      author: { id: 'user-3', name: 'Carlos Diaz', anonymousId: 'Installer #E5F6', avatarUrl: userAvatars['user-3'] },
      timestamp: new Date('2024-09-22T10:00:00Z'),
      content: "What brand of cameras are you planning to use? And is wiring already in place?",
    },
    {
      id: 'comment-1-2',
      author: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
      timestamp: new Date('2024-09-23T11:00:00Z'),
      content: "Hi Carlos, we're open to suggestions, but leaning towards Hikvision. No existing wiring, it needs to be run from scratch.",
    },
    {
      id: 'comment-1-3',
      author: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Installer #A1B2', avatarUrl: userAvatars['user-1'] },
      timestamp: new Date('2024-09-23T12:00:00Z'),
      content: "Is the building construction concrete or drywall? It will affect the cabling time.",
    },
     {
      id: 'comment-1-4',
      author: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
      timestamp: new Date('2024-09-23T13:00:00Z'),
      content: "It's a mix. Mostly drywall interiors with a concrete exterior.",
    }
  ],
  'JOB-20240924-4D5E': [
    {
      id: 'comment-5-1',
      author: { id: 'user-4', name: 'Diana Prince', anonymousId: 'Installer #G7H8', avatarUrl: userAvatars['user-4'] },
      timestamp: new Date('2024-09-23T14:00:00Z'),
      content: "Is this a single warehouse or multiple buildings?",
    },
     {
      id: 'comment-5-2',
      author: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
      timestamp: new Date('2024-09-24T09:00:00Z'),
      content: "It's a single large warehouse, approximately 50,000 sq ft.",
    }
  ],
   'JOB-20240925-P2Q3': [
    {
      id: 'comment-12-1',
      author: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Installer #A1B2', avatarUrl: userAvatars['user-1'] },
      timestamp: new Date('2024-09-26T10:00:00Z'),
      content: "I've reviewed the requirements. This seems straightforward. I can start on Monday.",
    },
  ],
};

const bids: {[key: string]: Bid[]} = {
  'JOB-20240920-1A3B': [
    {
      id: 'bid-1-1',
      installer: users[0],
      amount: 14000,
      timestamp: new Date('2024-09-21T18:00:00Z'),
      coverLetter: "With over 5 years of experience in IP camera systems and NVR setups, I can ensure a professional and clean installation. My bid includes all necessary cabling and configuration for remote viewing.",
    },
    {
      id: 'bid-1-2',
      installer: users[2],
      amount: 12500,
      timestamp: new Date('2024-09-22T09:00:00Z'),
      coverLetter: "I am confident I can complete this job to your satisfaction. I have experience with all major brands and can provide a cost-effective solution without compromising on quality.",
    },
    {
      id: 'bid-1-3',
      installer: users[4],
      amount: 18000,
      timestamp: new Date('2024-09-23T15:00:00Z'),
      coverLetter: "As a Platinum tier installer specializing in advanced systems, I can offer a premium installation with optimized camera placement and robust network configuration for flawless performance. My bid reflects a higher quality of service and components.",
    },
  ],
  'JOB-20240922-2B4C': [
     {
      id: 'bid-2-1',
      installer: users[3],
      amount: 9000,
      timestamp: new Date('2024-09-24T10:00:00Z'),
      coverLetter: "I can handle this upgrade efficiently. I'll ensure the new IP system is perfectly integrated.",
    },
  ],
  'JOB-20240915-3C5D': [
     {
      id: 'bid-3-1',
      installer: users[2],
      amount: 7500,
      timestamp: new Date('2024-09-14T10:00:00Z'),
      coverLetter: "I specialize in residential installations and can complete this quickly and cleanly. I guarantee a user-friendly setup for your mobile devices.",
    },
  ],
  'JOB-20240924-4D5E': [
     {
      id: 'bid-5-1',
      installer: users[4],
      amount: 48000,
      timestamp: new Date('2024-09-24T11:00:00Z'),
      coverLetter: "My team has extensive experience with large-scale warehouse projects. We use high-quality cabling and network gear to ensure reliable coverage across the entire area. We can also set up advanced analytics like line-crossing detection.",
    },
    {
      id: 'bid-5-2',
      installer: users[6],
      amount: 45000,
      timestamp: new Date('2024-09-24T12:00:00Z'),
      coverLetter: "I have installed systems in 5 warehouses in the last year. My bid is competitive and I can start next week.",
    },
  ],
  'JOB-20240917-5E6F': [
      {
      id: 'bid-6-1',
      installer: users[0],
      amount: 11000,
      timestamp: new Date('2024-09-22T14:00:00Z'),
      coverLetter: "I'm a Gold-tier installer with experience in retail environments. I can ensure minimal disruption to your business operations during the installation.",
    },
  ],
  'JOB-20240918-8J9K': [
    {
      id: 'bid-9-1',
      installer: users[0],
      amount: 6000,
      timestamp: new Date('2024-09-19T10:00:00Z'),
      coverLetter: "I can handle this residential setup. My work is clean and I will ensure you are happy with the camera placements.",
    }
  ],
  'JOB-20240801-K2L3': [
     {
      id: 'bid-10-1',
      installer: users[0],
      amount: 22000,
      timestamp: new Date('2024-07-25T10:00:00Z'),
      coverLetter: "Completed this project successfully.",
    },
  ],
   'JOB-20240925-P2Q3': [
    {
      id: 'bid-12-1',
      installer: users[0],
      amount: 28000,
      timestamp: new Date('2024-09-26T11:00:00Z'),
      coverLetter: "I have experience with multi-building wireless bridges and can ensure a seamless, unified system. My bid includes high-grade outdoor-rated equipment.",
    },
    {
      id: 'bid-12-2',
      installer: users[2],
      amount: 26500,
      timestamp: new Date('2024-09-26T14:00:00Z'),
      coverLetter: "My team can handle this campus-wide installation, including all trenching and cabling required for the fiber link between buildings.",
    },
  ],
  'JOB-20240928-R4S5': [
    {
      id: 'bid-13-1',
      installer: users[3],
      amount: 2800,
      timestamp: new Date('2024-09-29T09:00:00Z'),
      coverLetter: "I can troubleshoot your NVR and camera connectivity issues. I have a feeling it might be a network switch problem. I can diagnose and fix it.",
    },
  ],
  'JOB-20240910-T6U7': [
      {
      id: 'bid-14-1',
      installer: users[2],
      amount: 19000,
      timestamp: new Date('2024-09-08T12:00:00Z'),
      coverLetter: "My team and I can handle this.",
    },
  ]
};


export const jobs: Job[] = [
  {
    id: 'JOB-20240920-1A3B',
    title: 'Install 8 IP Cameras for a 2-Story Office Building',
    description: "We are looking for a professional installer to set up a comprehensive surveillance system for our new office. The job involves installing 8 high-definition IP cameras covering both indoor and outdoor areas. The installer will also be responsible for setting up the Network Video Recorder (NVR), configuring motion detection, and enabling remote viewing access on mobile devices. All equipment will be provided, but the installer must supply their own tools and manage all cabling and mounting.",
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '400001, Mumbai',
    budget: { min: 10000, max: 20000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-09-30T23:59:59Z'),
    postedAt: new Date('2024-09-20T08:00:00Z'),
    bids: bids['JOB-20240920-1A3B'],
    comments: comments['JOB-20240920-1A3B'],
  },
  {
    id: 'JOB-20240922-2B4C',
    title: 'CCTV System Upgrade for a Retail Store',
    description: "Upgrading an existing 4-camera analog system to a modern 6-camera IP system. The job requires removing the old DVR and cameras, and installing new IP cameras with a new NVR. The installer should be able to advise on optimal camera placement for maximum coverage of the sales floor and entrance/exit points. Experience with POS integration is a plus.",
    jobGiver: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Job Giver #A1B2', avatarUrl: userAvatars['user-1'] },
    location: '110001, Delhi',
    budget: { min: 8000, max: 15000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-03T23:59:59Z'),
    postedAt: new Date('2024-09-22T09:00:00Z'),
    bids: bids['JOB-20240922-2B4C'] || [],
    comments: [],
  },
  {
    id: 'JOB-20240915-3C5D',
    title: 'Residential 4-Camera Security Installation',
    description: "Seeking an installer for a standard 4-camera setup for a single-family home. Cameras to be placed at the front door, back door, driveway, and backyard. Simple setup with a DVR and mobile viewing required. Straightforward project for an experienced residential installer.",
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '600001, Chennai',
    budget: { min: 5000, max: 8000 },
    status: 'Awarded',
    awardedInstaller: 'user-3',
    deadline: new Date('2024-09-23T23:59:59Z'),
    postedAt: new Date('2024-09-15T11:00:00Z'),
    bids: bids['JOB-20240915-3C5D'],
    comments: [],
  },
  {
    id: 'JOB-20240825-4D6E',
    title: 'Maintenance and Check-up for existing system',
    description: "Need a technician to perform a full system check on our 16-camera setup. This includes cleaning lenses, checking all connections, ensuring the NVR is recording properly, and verifying that remote access is functional. The system is 2 years old.",
    jobGiver: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Job Giver #A1B2', avatarUrl: userAvatars['user-1'] },
    location: '500001, Hyderabad',
    budget: { min: 2000, max: 4000 },
    status: 'Completed',
    awardedInstaller: 'user-1',
    rating: 5,
    deadline: new Date('2024-08-26T23:59:59Z'),
    postedAt: new Date('2024-08-25T10:00:00Z'),
    bids: [],
    comments: [],
  },
  {
    id: 'JOB-20240924-4D5E',
    title: 'Install 32 PTZ Cameras in a Warehouse',
    description: 'We require a comprehensive surveillance solution for our new logistics warehouse. This involves installing 32 Pan-Tilt-Zoom (PTZ) cameras at strategic locations, setting up a centralized monitoring station with a Video Management System (VMS), and ensuring full wireless coverage across the facility. Only verified installers with experience in large-scale industrial projects should apply.',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '400050, Mumbai',
    budget: { min: 40000, max: 75000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-09T23:59:59Z'),
    postedAt: new Date('2024-09-24T14:00:00Z'),
    bids: bids['JOB-20240924-4D5E'],
    comments: comments['JOB-20240924-4D5E'],
  },
  {
    id: 'JOB-20240917-5E6F',
    title: 'Boutique Shop Camera Setup with Covert Cameras',
    description: 'Looking for a discreet security camera installation for a high-end boutique. The project requires 4-6 cameras, some of which must be covert or hidden. Aesthetics are very important. The system should be accessible remotely and have high-quality recording capabilities.',
    jobGiver: { id: 'user-8', name: 'Hannah Simone', anonymousId: 'Job Giver #O5P6', avatarUrl: userAvatars['user-8'] },
    location: '500032, Hyderabad',
    budget: { min: 9000, max: 18000 },
    status: 'Awarded',
    awardedInstaller: 'user-1',
    deadline: new Date('2024-09-24T23:59:59Z'),
    postedAt: new Date('2024-09-17T16:00:00Z'),
    bids: bids['JOB-20240917-5E6F'],
    comments: [],
  },
  {
    id: 'JOB-20240922-6F7G',
    title: 'Solar-Powered Camera for Remote Farm',
    description: 'Need to install one or two solar-powered 4G cameras to monitor a remote agricultural property. The location has no power or Wi-Fi. The installer must provide a complete solution including the solar panel, battery, and 4G camera setup. ',
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '800001, Patna',
    budget: { min: 15000, max: 25000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-05T23:59:59Z'),
    postedAt: new Date('2024-09-22T13:00:00Z'),
    bids: [],
    comments: [],
  },
  {
    id: 'JOB-20240816-7G8H',
    title: 'Apartment Complex Access Control & CCTV',
    description: 'We are seeking bids for a full security overall for a 50-unit apartment building. This includes installing cameras in all common areas (lobbies, hallways, parking) and setting up an access control system for the main entrance. The job will be awarded to a company that can handle both aspects.',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '110001, Delhi',
    budget: { min: 80000, max: 150000 },
    status: 'In Progress',
    awardedInstaller: 'user-5',
    deadline: new Date('2024-09-10T23:59:59Z'),
    postedAt: new Date('2024-08-16T12:00:00Z'),
    bids: [],
    comments: [],
  },
  {
    id: 'JOB-20240918-8J9K',
    title: '4 Camera setup for a new house',
    description: 'This is for a new house construction. Need 4 cameras installed. 2 outdoor, 2 indoor. All wiring needs to be concealed. The job giver will provide cameras and NVR.',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '400050, Mumbai',
    budget: { min: 5000, max: 9000 },
    status: 'Cancelled',
    awardedInstaller: 'user-1',
    deadline: new Date('2024-09-25T23:59:59Z'),
    postedAt: new Date('2024-09-18T11:00:00Z'),
    bids: bids['JOB-20240918-8J9K'],
    comments: [],
  },
  {
    id: 'JOB-20240801-K2L3',
    title: 'Corporate Office Full Security System',
    description: 'Installation of 15 cameras, access control on 5 doors, and a central monitoring room setup for a corporate office. High-end equipment required.',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '500032, Hyderabad',
    budget: { min: 20000, max: 30000 },
    status: 'Completed',
    awardedInstaller: 'user-1',
    rating: 4,
    deadline: new Date('2024-08-10T23:59:59Z'),
    postedAt: new Date('2024-08-01T10:00:00Z'),
    bids: bids['JOB-20240801-K2L3'],
    comments: [],
  },
  {
    id: 'JOB-20240715-M4N5',
    title: 'School Campus Camera Overhaul',
    description: 'Full overhaul of a school campus security system. Requires 20+ cameras, NVR, and integration with an existing alert system.',
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '110001, Delhi',
    budget: { min: 50000, max: 80000 },
    status: 'Completed',
    awardedInstaller: 'user-1',
    rating: 5,
    deadline: new Date('2024-07-25T23:59:59Z'),
    postedAt: new Date('2024-07-15T09:00:00Z'),
    bids: [],
    comments: [],
  },
  {
    id: 'JOB-20240925-P2Q3',
    title: 'Connect Two Buildings with Wireless Bridge',
    description: 'We need to link the camera systems of two adjacent buildings. This requires setting up a point-to-point wireless bridge. The distance is approximately 200 meters with clear line of sight. The goal is to have a unified view of cameras from both buildings on a single NVR.',
    jobGiver: { id: 'user-1', name: 'Alex Johnson', anonymousId: 'Job Giver #A1B2', avatarUrl: userAvatars['user-1'] },
    location: '500001, Hyderabad',
    budget: { min: 25000, max: 40000 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-02T23:59:59Z'),
    postedAt: new Date('2024-09-25T09:00:00Z'),
    bids: bids['JOB-20240925-P2Q3'],
    comments: comments['JOB-20240925-P2Q3'],
  },
  {
    id: 'JOB-20240928-R4S5',
    title: 'Troubleshoot NVR Not Recording',
    description: 'Our 8-camera NVR has stopped recording on 3 channels. The live view is working fine, but no footage is being saved from the affected cameras. We need an experienced technician to diagnose and fix the issue. Might be a hard drive issue or configuration problem.',
    jobGiver: { id: 'user-8', name: 'Hannah Simone', anonymousId: 'Job Giver #O5P6', avatarUrl: userAvatars['user-8'] },
    location: '500032, Hyderabad',
    budget: { min: 2000, max: 3500 },
    status: 'Open for Bidding',
    deadline: new Date('2024-10-01T23:59:59Z'),
    postedAt: new Date('2024-09-28T10:00:00Z'),
    bids: bids['JOB-20240928-R4S5'],
    comments: [],
  },
  {
    id: 'JOB-20240910-T6U7',
    title: 'Cafe Interior and Exterior Camera Setup',
    description: 'Setting up 4 dome cameras inside a small cafe and 2 bullet cameras for the exterior. Need clear footage of the entrance and seating areas. The job includes all wiring and setup on a new NVR system.',
    jobGiver: { id: 'user-2', name: 'Brenda Smith', anonymousId: 'Job Giver #C3D4', avatarUrl: userAvatars['user-2'] },
    location: '600001, Chennai',
    budget: { min: 15000, max: 22000 },
    status: 'Completed',
    awardedInstaller: 'user-3',
    rating: 5,
    deadline: new Date('2024-09-15T23:59:59Z'),
    postedAt: new Date('2024-09-10T11:00:00Z'),
    bids: bids['JOB-20240910-T6U7'],
    comments: [],
  },
  {
    id: 'JOB-20240905-V8W9',
    title: 'Bidding Closed Job Example',
    description: 'This is a job where the bidding period has ended, but the job giver has not yet selected an installer. It should appear as "Bidding Closed".',
    jobGiver: { id: 'user-6', name: 'Fiona Glenanne', anonymousId: 'Job Giver #K1L2', avatarUrl: userAvatars['user-6'] },
    location: '800001, Patna',
    budget: { min: 5000, max: 10000 },
    status: 'Bidding Closed',
    deadline: new Date('2024-09-10T23:59:59Z'),
    postedAt: new Date('2024-09-05T15:00:00Z'),
    bids: [
      {
        id: 'bid-15-1',
        installer: users[6],
        amount: 8000,
        timestamp: new Date('2024-09-06T10:00:00Z'),
        coverLetter: "I'm available to start immediately.",
      },
    ],
    comments: [],
  },
];
