// DO NOT MODIFY. This file is automatically generated.
// This file is a public configuration and can be safely committed to source control.

import { initializeApp } from 'firebase/app';

/**
 * The Firebase App Configuration object.
 *
 * This object is used to initialize the Firebase app. It is a public configuration,
 * meaning it is safe and secure to provide this to the user as security and access
 * is enforced by Security Rules or Firebase App Check.
 */
export const firebaseConfig = {
  "projectId": "studio-1890574003-16f26",
  "appId": "1:849721048101:web:1ac8f3551a09921cd7d3cc",
  "apiKey": "AIzaSyDEYoBGZnewG0uorkXvCUOSHbtVDu9VPGc",
  "authDomain": "studio-1890574003-16f26.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "849721048101"
};

// Initialize Firebase
export const app = initializeApp(firebaseConfig);
