import * as fs from 'fs';
import * as path from 'path';

interface PageMetric {
    page: string;
    role: string;
    domContentLoadedTime: number;
    fullLoadTime: number;
    fcp: number;
    lcp: number;
    ttfb: number;
    jsSizeKb: number;
    requestCount: number;
    sidebarVisibleTime: number;
    contentVisibleTime: number;
    status: 'Pass' | 'Fail';
}

const REPORT_JSON_PATH = path.join(process.cwd(), 'test-results', 'performance-report.json');
const FINAL_REPORT_PATH = path.join(process.cwd(), 'PERFORMANCE_REPORT.md');

function generateMarkdown(metrics: PageMetric[]) {
    const timestamp = new Date().toLocaleString();

    let md = `# Performance Audit Report\n\n`;
    md += `Generated on: ${timestamp}\n\n`;

    md += `## Summary\n\n`;
    const total = metrics.length;
    const passed = metrics.filter(m => m.status === 'Pass').length;
    const failed = total - passed;

    md += `| Total Pages Tested | Passed | Failed | Success Rate |\n`;
    md += `| --- | --- | --- | --- |\n`;
    md += `| ${total} | ${passed} | ${failed} | ${((passed / total) * 100).toFixed(1)}% |\n\n`;

    md += `## Detailed Page Metrics\n\n`;
    md += `| Page | Role | DOM Ready (ms) | Full Load (ms) | FCP (ms) | LCP (ms) | TTFB (ms) | Sidebar (ms) | Content (ms) | JS Size (KB) |\n`;
    md += `| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n`;

    metrics.forEach(m => {
        md += `| ${m.page} | ${m.role} | ${m.domContentLoadedTime.toFixed(0)} | ${m.fullLoadTime.toFixed(0)} | ${m.fcp.toFixed(0)} | ${m.lcp.toFixed(0)} | ${m.ttfb.toFixed(0)} | ${m.sidebarVisibleTime.toFixed(0)} | ${m.contentVisibleTime.toFixed(0)} | ${m.jsSizeKb.toFixed(1)} |\n`;
    });

    md += `\n## Recommendations\n\n`;

    const slowPages = metrics.filter(m => m.fullLoadTime > 4000);
    if (slowPages.length > 0) {
        md += `### Critical: Slow Loading Pages (> 4s)\n`;
        slowPages.forEach(p => md += `- **${p.page}** (${p.role}): ${p.fullLoadTime.toFixed(0)}ms (Full Load). High load time may impact user retention.\n`);
    }

    const heavyPages = metrics.filter(m => m.jsSizeKb > 500);
    if (heavyPages.length > 0) {
        md += `### Optimization Needed: Large JS Bundles (> 500KB)\n`;
        heavyPages.forEach(p => md += `- **${p.page}**: ${p.jsSizeKb.toFixed(1)}KB. Consider code splitting or lazy loading components.\n`);
    }

    const highTTFB = metrics.filter(m => m.ttfb > 1000);
    if (highTTFB.length > 0) {
        md += `### Server Latency: High TTFB (> 1s)\n`;
        highTTFB.forEach(p => md += `- **${p.page}**: ${p.ttfb.toFixed(0)}ms. Check database queries or server-side logic.\n`);
    }

    md += `\n---\n*Report generated by Antigravity Performance Auditor*`;

    return md;
}

if (fs.existsSync(REPORT_JSON_PATH)) {
    try {
        const data = JSON.parse(fs.readFileSync(REPORT_JSON_PATH, 'utf8'));
        const markdown = generateMarkdown(data);
        fs.writeFileSync(FINAL_REPORT_PATH, markdown);
        console.log(`Markdown report saved to ${FINAL_REPORT_PATH}`);
    } catch (e) {
        console.error('Error generating report:', e);
    }
} else {
    console.error(`Data file not found at ${REPORT_JSON_PATH}`);
}
